# Ensure the site always serves index.html for Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle static files
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true
